services:
  postgres-dev:
    build:
      context: .
      dockerfile: ./database/Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - 9400:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  postgres-test:
    build:
      context: .
      dockerfile: ./database/Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    ports:
      - 9401:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    depends_on:
      postgres-dev:
        condition: service_healthy
  lgtm:
    image: docker.io/grafana/otel-lgtm:0.8.1
    container_name: lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./lgtm/grafana:/data/grafana
      - ./lgtm/prometheus:/data/prometheus
      - ./lgtm/loki:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    restart: unless-stopped
    tty: true
    stdin_open: true
