services:
  postgres-dev:
    build:
      context: .
      dockerfile: ./database/Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - 9400:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  postgres-test:
    build:
      context: .
      dockerfile: ./database/Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    ports:
      - 9401:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    depends_on:
      postgres-dev:
        condition: service_healthy
