// This is a placeholder for the app.tsx file.
// This will later be auto generated by the build script.
// Similar to _main.tsx from @udibo/react-app routes directory.

export default function App() {
  return <div>Hello World!</div>;
}
