// This file is auto-generated by @udibo/juniper/build
// Do not edit this file directly.

import { createServer } from "@udibo/juniper/server";

import { client } from "./main.tsx";

export const server = createServer(import.meta.url, client, {
  path: "/",
  main: await import("./routes/main.ts"),
  children: [
    {
      path: "api",
      main: await import("./routes/api/main.ts"),
      children: [
        {
          path: "users",
          main: await import("./routes/api/users.ts"),
        },
        {
          path: "blog",
          children: [
            {
              path: "posts",
              main: await import("./routes/api/blog/posts.ts"),
            },
          ],
        },
      ],
    },
    {
      path: "blog",
      index: await import("./routes/blog/index.ts"),
      children: [
        {
          path: "create",
          main: await import("./routes/blog/create.ts"),
        },
        {
          path: ":id",
          index: await import("./routes/blog/[id]/index.ts"),
          children: [
            {
              path: "edit",
              main: await import("./routes/blog/[id]/edit.ts"),
            },
          ],
        },
      ],
    },
    {
      path: "features",
      children: [
        {
          path: "data",
          children: [
            {
              path: "parent-data",
              main: await import("./routes/features/data/parent-data/main.ts"),
            },
            {
              path: "server-actions",
              children: [
                {
                  path: "client-calls-server",
                  main: await import(
                    "./routes/features/data/server-actions/client-calls-server.ts"
                  ),
                },
                {
                  path: "object",
                  main: await import(
                    "./routes/features/data/server-actions/object.ts"
                  ),
                },
                {
                  path: "redirect",
                  main: await import(
                    "./routes/features/data/server-actions/redirect.ts"
                  ),
                },
                {
                  path: "response",
                  main: await import(
                    "./routes/features/data/server-actions/response.ts"
                  ),
                },
              ],
            },
            {
              path: "server-loaders",
              children: [
                {
                  path: "client-calls-server",
                  main: await import(
                    "./routes/features/data/server-loaders/client-calls-server.ts"
                  ),
                },
                {
                  path: "object",
                  main: await import(
                    "./routes/features/data/server-loaders/object.ts"
                  ),
                },
                {
                  path: "redirect",
                  main: await import(
                    "./routes/features/data/server-loaders/redirect.ts"
                  ),
                },
                {
                  path: "response",
                  main: await import(
                    "./routes/features/data/server-loaders/response.ts"
                  ),
                },
              ],
            },
          ],
        },
        {
          path: "errors",
          children: [
            {
              path: "server-loader",
              main: await import("./routes/features/errors/server-loader.ts"),
            },
            {
              path: "server-middleware",
              main: await import(
                "./routes/features/errors/server-middleware.ts"
              ),
            },
            {
              path: "ssr",
              main: await import("./routes/features/errors/ssr.ts"),
            },
            {
              path: "nested",
            },
          ],
        },
        {
          path: "middleware",
          children: [
            {
              path: "basic-auth",
              main: await import("./routes/features/middleware/basic-auth.ts"),
            },
            {
              path: "client-middleware",
              main: await import(
                "./routes/features/middleware/client-middleware.ts"
              ),
            },
            {
              path: "combined",
              main: await import("./routes/features/middleware/combined.ts"),
            },
            {
              path: "context-sharing",
              main: await import(
                "./routes/features/middleware/context-sharing.ts"
              ),
            },
          ],
        },
        {
          path: "routing",
          children: [
            {
              path: "files",
            },
            {
              path: "post",
            },
            {
              path: "settings",
            },
            {
              path: "user",
              children: [
                {
                  path: ":userId",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
});

if (import.meta.main) {
  Deno.serve(server.fetch);
}
