// This file is auto-generated by @udibo/juniper/build
// Do not edit this file directly.

import { createClient, hydrate } from "@udibo/juniper/client";
import { isBrowser } from "@udibo/juniper/utils/env";

export const client = createClient({
  path: "/",
  main: await import("./routes/main.tsx"),
  index: () => import("./routes/index.tsx"),
  children: [
    {
      path: "/about",
      main: () => import("./routes/about.tsx"),
    },
    {
      path: "/blog",
      main: () => import("./routes/blog/main.tsx"),
      index: () => import("./routes/blog/index.tsx"),
      children: [
        {
          path: "/:id",
          main: () => import("./routes/blog/[id].tsx"),
        },
      ],
    },
  ],
});

if (isBrowser()) {
  hydrate(client);
}
