// This file is auto-generated by @udibo/juniper/build
// Do not edit this file directly.

import { Client } from "@udibo/juniper/client";

export const client = new Client({
  path: "/",
  main: await import("./routes/main.tsx"),
  index: () => import("./routes/index.tsx"),
  children: [
    {
      path: "blog",
      main: () => import("./routes/blog/main.tsx"),
      index: () => import("./routes/blog/index.tsx"),
      children: [
        {
          path: ":id",
          main: () => import("./routes/blog/[id].tsx"),
        },
      ],
    },
    {
      path: "features",
      main: () => import("./routes/features/main.tsx"),
      index: () => import("./routes/features/index.tsx"),
      children: [
        {
          path: "data",
          children: [
            {
              path: "action",
              main: () => import("./routes/features/data/action.tsx"),
            },
            {
              path: "deferred",
              main: () => import("./routes/features/data/deferred.tsx"),
            },
            {
              path: "fetcher",
              main: () => import("./routes/features/data/fetcher.tsx"),
            },
            {
              path: "hydrate-fallback",
              main: () => import("./routes/features/data/hydrate-fallback.tsx"),
            },
            {
              path: "loader",
              main: () => import("./routes/features/data/loader.tsx"),
            },
          ],
        },
        {
          path: "errors",
          main: () => import("./routes/features/errors/main.tsx"),
          children: [
            {
              path: "boundary",
              main: () => import("./routes/features/errors/boundary.tsx"),
            },
            {
              path: "ssr",
              main: () => import("./routes/features/errors/ssr.tsx"),
            },
          ],
        },
        {
          path: "routing",
          index: () => import("./routes/features/routing/index.tsx"),
          children: [
            {
              path: "files",
              catchall: () =>
                import("./routes/features/routing/files/[...].tsx"),
            },
            {
              path: "post",
              children: [
                {
                  path: ":id",
                  main: () => import("./routes/features/routing/post/[id].tsx"),
                },
              ],
            },
            {
              path: "settings",
              children: [
                {
                  path: "appearance",
                  main: () =>
                    import("./routes/features/routing/settings/appearance.tsx"),
                },
              ],
            },
            {
              path: "user",
              children: [
                {
                  path: ":userId",
                  children: [
                    {
                      path: "profile",
                      main: () =>
                        import(
                          "./routes/features/routing/user/[userId]/profile.tsx"
                        ),
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
});
