// This file is auto-generated by @udibo/juniper/build
// Do not edit this file directly.

import { createServer } from "@udibo/juniper/server";

import { client } from "./main.tsx";

export const server = createServer(import.meta.url, client, {
  path: "/",
  main: await import("./routes/main.ts"),
  children: [
    {
      path: "api",
      main: await import("./routes/api/main.ts"),
      children: [
        {
          path: "users",
          main: await import("./routes/api/users.ts"),
        },
        {
          path: "blog",
          children: [
            {
              path: "posts",
              main: await import("./routes/api/blog/posts.ts"),
            },
          ],
        },
      ],
    },
    {
      path: "blog",
    },
    {
      path: "features",
      children: [
        {
          path: "data",
        },
        {
          path: "errors",
        },
        {
          path: "routing",
          children: [
            {
              path: "files",
            },
            {
              path: "post",
            },
            {
              path: "settings",
            },
            {
              path: "user",
              children: [
                {
                  path: ":userId",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
});

if (import.meta.main) {
  Deno.serve(server.fetch);
}
