// This file is auto-generated by @udibo/juniper/build
// Do not edit this file directly.

import { createServer } from "@udibo/juniper/server";

import { client } from "./main.tsx";

export const server = createServer(import.meta.url, client, {
  path: "/",
  main: await import("./routes/main.ts"),
});

if (import.meta.main) {
  Deno.serve(server.fetch);
}
