/**
 * This module contains the server-side runtime for Juniper applications.
 *
 * It provides the {@linkcode createServer} function for creating Hono applications
 * with integrated routing, static file serving, and server-side rendering.
 *
 * @module
 */
import * as path from "@std/path";
import { HttpError } from "./mod.ts";
import { Hono } from "hono";
import type { Schema } from "hono";
import { etag } from "hono/etag";
import { trimTrailingSlash } from "hono/trailing-slash";
import { RouterContextProvider } from "react-router";

import type { Client } from "./client.tsx";
import { getInstance } from "./utils/otel.ts";

import {
  buildApp,
  createHandlers,
  isRedirectResponse,
  mergeServerRoutes,
  toRedirectEnvelope,
} from "./_server.tsx";
import type { AppEnv, Route } from "./_server.tsx";

export type { AppEnv };

/**
 * Creates a Hono application server with the provided route configuration.
 * The main entrypoint that uses this function is automatically generated by the build script.
 *
 * This function sets up error handling, trailing slash trimming, static file serving,
 * and builds the complete route tree from the provided configuration, merging both
 * client and server routes.
 *
 * @example Creating an application
 * ```ts
 * import { createServer } from "@udibo/juniper/server";
 * import { client } from "./main.tsx";
 *
 * export const server = createServer(import.meta.url, client, {
 *   path: "/",
 *   main: await import("./routes/main.ts"),
 *   children: [
 *     {
 *       path: "/api",
 *       main: await import("./routes/api/main.ts"),
 *       children: [
 *         {
 *           path: "/users",
 *           main: await import("./routes/api/users.ts"),
 *         }
 *       ]
 *     }
 *   ],
 * });
 *
 * if (import.meta.main) {
 *   Deno.serve(server.fetch);
 * }
 * ```
 *
 * @template E - Hono environment type
 * @template S - Hono schema type
 * @template BasePath - Base path string type
 *
 * @param moduleUrl - The URL of the module creating the server
 * @param client - The client configuration
 * @param routes - The server route configuration object
 * @returns A configured Hono application instance
 */
export function createServer<
  E extends AppEnv = AppEnv,
  S extends Schema = Schema,
  BasePath extends string = "/",
>(
  moduleUrl: string,
  client: Client,
  route: Route<E, S, BasePath>,
): Hono<E, S, BasePath> {
  const projectRoot = path.dirname(path.fromFileUrl(moduleUrl));
  const appWrapper = new Hono<E, S, BasePath>({ strict: true });

  appWrapper.use(async (c, next) => {
    c.set("context", new RouterContextProvider());
    await next();
    // Client-side (data-mode) navigations fetch loader/action data with an
    // `X-Juniper-Route-Id` header and expect a redirect envelope, not a raw 3xx
    // that `fetch` would silently follow. Repackage ANY redirect that surfaces
    // on such a request — including one from a Hono handler/middleware that
    // short-circuited before the React Router handlers (e.g. an auth guard's
    // `c.redirect()`, or a `return redirectDocument()`) — into that envelope,
    // honoring `redirectDocument()` (full-page) vs `redirect()` (SPA) uniformly.
    // Document requests carry no such header and keep their browser-followed
    // 302s. Loader/action redirects are already enveloped (status 200) by
    // `handleDataRequest`, so `isRedirectResponse` skips them here.
    if (c.req.header("X-Juniper-Route-Id") && isRedirectResponse(c.res)) {
      c.res = toRedirectEnvelope(c.res);
      // Assigning `c.res` merges the prior response's headers in; drop the ones
      // that must not appear on the 200 envelope (they live in the body).
      c.res.headers.delete("Location");
      c.res.headers.delete("X-Remix-Reload-Document");
    }
  });

  appWrapper.use(trimTrailingSlash());

  appWrapper.use("/build/main.js", etag(), async (c, next) => {
    c.header("Cache-Control", "private, no-cache, must-revalidate, max-age=0");
    await next();
  });
  appWrapper.use("/build/*", async (c, next) => {
    const pathname = new URL(c.req.url).pathname;
    if (pathname !== "/build/main.js") {
      c.header("Cache-Control", "public, max-age=14400");
    }
    await next();
  });

  appWrapper.onError((cause) => {
    if (
      !(cause instanceof HttpError) &&
      cause !== null &&
      typeof cause === "object" &&
      "getResponse" in cause &&
      typeof cause.getResponse === "function"
    ) {
      console.error(cause);
      return cause.getResponse();
    }
    const error = HttpError.from(cause);
    if (!error.instance) {
      const instance = getInstance();
      if (instance) {
        error.instance = instance;
      }
    }
    console.error(error);
    return error.getResponse();
  });

  const serverRoutes = mergeServerRoutes(route, client.routeObjects);
  const { handlers, errorHandler } = createHandlers(
    route,
    serverRoutes,
    client.htmlProps,
  );
  const app = buildApp(
    route,
    client.rootRoute,
    handlers,
    projectRoot,
    "/",
    errorHandler,
  );

  appWrapper.route("/", app);
  return appWrapper;
}
