name: CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DENO_DIR: .cache/deno
      DATABASE_URL: ${{ github.event_name == 'push' && secrets.DATABASE_URL_PRODUCTION || secrets.DATABASE_URL_DEVELOPMENT }}
      USE_NEON: true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-${{ hashFiles('deno.lock') }}
      - name: Apply migrations
        run: deno task drizzle-kit migrate
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ github.event_name == 'push' && 'juniper' || 'juniper-preview' }}
          entrypoint: ./example/main.ts
