name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  formatAndLint:
    name: Check formatting and lint
    runs-on: ubuntu-latest
    env:
      DENO_DIR: .cache/deno
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-${{ hashFiles('deno.lock') }}
      - name: Check formatting
        run: deno fmt --check
      - name: Lint source files
        run: deno lint
  test-build:
    name: Test build on ${{ matrix.os }}
    needs: [formatAndLint]
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    env:
      DENO_DIR: .cache/deno
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-${{ hashFiles('deno.lock') }}
      - name: Run tests for build
        run: deno test -A --env-file --env-file=.env.test --trace-leaks build.test.ts
  test:
    name: Test
    needs: [build-postgres-image]
    runs-on: ubuntu-latest
    env:
      DENO_DIR: .cache/deno
      DATABASE_URL: postgresql://test:password@localhost:5432/test
    services:
      postgres-test:
        image: ghcr.io/${{ github.repository_owner }}/postgres-test:latest
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-${{ hashFiles('deno.lock') }}
      - name: Run tests and collect coverage
        run: deno task test --coverage
      - name: View coverage report
        run: deno coverage --detailed
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  build-postgres-image:
    name: Build PostgreSQL Test Image
    needs: [formatAndLint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push postgres test image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./example/database/Dockerfile.postgres
          tags: ghcr.io/${{ github.repository_owner }}/postgres-test:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
